//
// File generated by rootcint at Tue Dec 16 10:43:42 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME NTupleDictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NTupleDictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
static struct DictInit {
    DictInit() {
        ROOT::RegisterModule();
    }
} __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
namespace Shadow {
} // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
void Detector_ShowMembers(void *obj, TMemberInspector &R__insp);
static void *new_Detector(void *p = 0);
static void *newArray_Detector(Long_t size, void *p);
static void delete_Detector(void *p);
static void deleteArray_Detector(void *p);
static void destruct_Detector(void *p);

// Function generating the singleton type initializer
static TGenericClassInfo *GenerateInitInstanceLocal(const ::Detector*)
{
    ::Detector *ptr = 0;
    static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Detector >(0);
    static ::ROOT::TGenericClassInfo
            instance("Detector", ::Detector::Class_Version(), "./Griffin.hh", 6,
                     typeid(::Detector), DefineBehavior(ptr, ptr),
                     &::Detector::Dictionary, isa_proxy, 4,
                     sizeof(::Detector) );
    instance.SetNew(&new_Detector);
    instance.SetNewArray(&newArray_Detector);
    instance.SetDelete(&delete_Detector);
    instance.SetDeleteArray(&deleteArray_Detector);
    instance.SetDestructor(&destruct_Detector);
    return &instance;
}
TGenericClassInfo *GenerateInitInstance(const ::Detector*)
{
    return GenerateInitInstanceLocal((::Detector*)0);
}
// Static variable to force the class initialization
static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Detector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Detector::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Detector::Class_Name()
{
    return "Detector";
}

//______________________________________________________________________________
const char *Detector::ImplFileName()
{
    return ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Detector::ImplFileLine()
{
    return ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Detector::Dictionary()
{
    fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Detector::Class()
{
    if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetClass();
    return fgIsA;
}

//______________________________________________________________________________
void Detector::Streamer(TBuffer &R__b)
{
    // Stream an object of class Detector.

    if (R__b.IsReading()) {
        R__b.ReadClassBuffer(Detector::Class(),this);
    } else {
        R__b.WriteClassBuffer(Detector::Class(),this);
    }
}

//______________________________________________________________________________
void Detector::ShowMembers(TMemberInspector &R__insp)
{
    // Inspect the data members of an object of class Detector.
    TClass *R__cl = ::Detector::IsA();
    if (R__cl || R__insp.IsA()) { }
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fEventNumber", &fEventNumber);
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fDetectorId", &fDetectorId);
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fCrystalId", &fCrystalId);
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fSimulationEnergy", &fSimulationEnergy);
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fEnergy", &fEnergy);
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosition", &fPosition);
    R__insp.InspectMember(fPosition, "fPosition.");
    R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &fTime);
    TObject::ShowMembers(R__insp);
}

namespace ROOT {
// Wrappers around operator new
static void *new_Detector(void *p) {
    return  p ? new(p) ::Detector : new ::Detector;
}
static void *newArray_Detector(Long_t nElements, void *p) {
    return p ? new(p) ::Detector[nElements] : new ::Detector[nElements];
}
// Wrapper around operator delete
static void delete_Detector(void *p) {
    delete ((::Detector*)p);
}
static void deleteArray_Detector(void *p) {
    delete [] ((::Detector*)p);
}
static void destruct_Detector(void *p) {
    typedef ::Detector current_t;
    ((current_t*)p)->~current_t();
}
} // end of namespace ROOT for class ::Detector

namespace ROOT {
void vectorlEDetectorgR_ShowMembers(void *obj, TMemberInspector &R__insp);
static void vectorlEDetectorgR_Dictionary();
static void *new_vectorlEDetectorgR(void *p = 0);
static void *newArray_vectorlEDetectorgR(Long_t size, void *p);
static void delete_vectorlEDetectorgR(void *p);
static void deleteArray_vectorlEDetectorgR(void *p);
static void destruct_vectorlEDetectorgR(void *p);

// Function generating the singleton type initializer
static TGenericClassInfo *GenerateInitInstanceLocal(const vector<Detector>*)
{
    vector<Detector> *ptr = 0;
    static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<Detector>),0);
    static ::ROOT::TGenericClassInfo
            instance("vector<Detector>", -2, "prec_stl/vector", 49,
                     typeid(vector<Detector>), DefineBehavior(ptr, ptr),
                     0, &vectorlEDetectorgR_Dictionary, isa_proxy, 4,
                     sizeof(vector<Detector>) );
    instance.SetNew(&new_vectorlEDetectorgR);
    instance.SetNewArray(&newArray_vectorlEDetectorgR);
    instance.SetDelete(&delete_vectorlEDetectorgR);
    instance.SetDeleteArray(&deleteArray_vectorlEDetectorgR);
    instance.SetDestructor(&destruct_vectorlEDetectorgR);
    instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<Detector> >()));
    return &instance;
}
// Static variable to force the class initialization
static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<Detector>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

// Dictionary for non-ClassDef classes
static void vectorlEDetectorgR_Dictionary() {
    ::ROOT::GenerateInitInstanceLocal((const vector<Detector>*)0x0)->GetClass();
}

} // end of namespace ROOT

namespace ROOT {
// Wrappers around operator new
static void *new_vectorlEDetectorgR(void *p) {
    return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<Detector> : new vector<Detector>;
}
static void *newArray_vectorlEDetectorgR(Long_t nElements, void *p) {
    return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<Detector>[nElements] : new vector<Detector>[nElements];
}
// Wrapper around operator delete
static void delete_vectorlEDetectorgR(void *p) {
    delete ((vector<Detector>*)p);
}
static void deleteArray_vectorlEDetectorgR(void *p) {
    delete [] ((vector<Detector>*)p);
}
static void destruct_vectorlEDetectorgR(void *p) {
    typedef vector<Detector> current_t;
    ((current_t*)p)->~current_t();
}
} // end of namespace ROOT for class vector<Detector>

/********************************************************
* NTupleDictionary.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNTupleDictionary();

extern "C" void G__set_cpp_environmentNTupleDictionary() {
    G__add_compiledheader("TObject.h");
    G__add_compiledheader("TMemberInspector.h");
    G__add_compiledheader("Griffin.hh");
    G__cpp_reset_tagtableNTupleDictionary();
}
#include <new>
extern "C" int G__cpp_dllrevNTupleDictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Detector */
static int G__NTupleDictionary_220_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    Detector* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
            p = new Detector[n];
        } else {
            p = new((void*) gvp) Detector[n];
        }
    } else {
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
            p = new Detector;
        } else {
            p = new((void*) gvp) Detector;
        }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector));
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    Detector* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 7
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new Detector(
                    (int) G__int(libp->para[0]), (int) G__int(libp->para[1])
                    , (int) G__int(libp->para[2]), (double) G__double(libp->para[3])
                    , (double) G__double(libp->para[4]), *((TVector3*) G__int(libp->para[5]))
                    , (double) G__double(libp->para[6]));
    } else {
        p = new((void*) gvp) Detector(
                    (int) G__int(libp->para[0]), (int) G__int(libp->para[1])
                    , (int) G__int(libp->para[2]), (double) G__double(libp->para[3])
                    , (double) G__double(libp->para[4]), *((TVector3*) G__int(libp->para[5]))
                    , (double) G__double(libp->para[6]));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector));
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((Detector*) G__getstructoffset())->AddEnergy((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((Detector*) G__getstructoffset())->Set(
                (int) G__int(libp->para[0]), (int) G__int(libp->para[1])
                , (int) G__int(libp->para[2]), (double) G__double(libp->para[3])
                , (double) G__double(libp->para[4]), *((TVector3*) G__int(libp->para[5]))
                , (double) G__double(libp->para[6]));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((Detector*) G__getstructoffset())->Clear();
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 105, (long) ((Detector*) G__getstructoffset())->EventNumber());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 105, (long) ((Detector*) G__getstructoffset())->DetectorId());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 105, (long) ((Detector*) G__getstructoffset())->CrystalId());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letdouble(result7, 100, (double) ((Detector*) G__getstructoffset())->SimulationEnergy());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letdouble(result7, 100, (double) ((Detector*) G__getstructoffset())->Energy());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        TVector3* pobj;
        TVector3 xobj = ((Detector*) G__getstructoffset())->Position();
        pobj = new TVector3(xobj);
        result7->obj.i = (long) ((void*) pobj);
        result7->ref = result7->obj.i;
        G__store_tempobject(*result7);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letdouble(result7, 100, (double) ((Detector*) G__getstructoffset())->Time());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 85, (long) Detector::Class());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 67, (long) Detector::Class_Name());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 115, (long) Detector::Class_Version());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    Detector::Dictionary();
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((Detector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 67, (long) Detector::DeclFileName());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 105, (long) Detector::ImplFileLine());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 67, (long) Detector::ImplFileName());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_220_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 105, (long) Detector::DeclFileLine());
    return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NTupleDictionary_220_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
    Detector* p;
    void* tmp = (void*) G__int(libp->para[0]);
    p = new Detector(*(Detector*) tmp);
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector));
    return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Detector G__TDetector;
static int G__NTupleDictionary_220_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 1
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
        return(1);
    }
    if (n) {
        if (gvp == (char*)G__PVOID) {
            delete[] (Detector*) soff;
        } else {
            G__setgvp((long) G__PVOID);
            for (int i = n - 1; i >= 0; --i) {
                ((Detector*) (soff+(sizeof(Detector)*i)))->~G__TDetector();
            }
            G__setgvp((long)gvp);
        }
    } else {
        if (gvp == (char*)G__PVOID) {
            delete (Detector*) soff;
        } else {
            G__setgvp((long) G__PVOID);
            ((Detector*) (soff))->~G__TDetector();
            G__setgvp((long)gvp);
        }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NTupleDictionary_220_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    Detector* dest = (Detector*) G__getstructoffset();
    *dest = *(Detector*) libp->para[0].ref;
    const Detector& obj = *dest;
    result7->ref = (long) (&obj);
    result7->obj.i = (long) (&obj);
    return(1 || funcname || hash || result7 || libp) ;
}


/* vector<Detector,allocator<Detector> > */
static int G__NTupleDictionary_222_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        const vector<Detector,allocator<Detector> >::reference obj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->at((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::const_reference obj = ((const vector<Detector,allocator<Detector> >*) G__getstructoffset())->at((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::iterator* pobj;
        vector<Detector,allocator<Detector> >::iterator xobj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->begin();
        pobj = new vector<Detector,allocator<Detector> >::iterator(xobj);
        result7->obj.i = (long) ((void*) pobj);
        result7->ref = result7->obj.i;
        G__store_tempobject(*result7);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::iterator* pobj;
        vector<Detector,allocator<Detector> >::iterator xobj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->end();
        pobj = new vector<Detector,allocator<Detector> >::iterator(xobj);
        result7->obj.i = (long) ((void*) pobj);
        result7->ref = result7->obj.i;
        G__store_tempobject(*result7);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::reverse_iterator* pobj;
        vector<Detector,allocator<Detector> >::reverse_iterator xobj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->rbegin();
        pobj = new vector<Detector,allocator<Detector> >::reverse_iterator(xobj);
        result7->obj.i = (long) ((void*) pobj);
        result7->ref = result7->obj.i;
        G__store_tempobject(*result7);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::reverse_iterator* pobj;
        vector<Detector,allocator<Detector> >::reverse_iterator xobj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->rend();
        pobj = new vector<Detector,allocator<Detector> >::reverse_iterator(xobj);
        result7->obj.i = (long) ((void*) pobj);
        result7->ref = result7->obj.i;
        G__store_tempobject(*result7);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 107, (long) ((const vector<Detector,allocator<Detector> >*) G__getstructoffset())->size());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 107, (long) ((const vector<Detector,allocator<Detector> >*) G__getstructoffset())->max_size());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->resize((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->resize((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]), *((Detector*) G__int(libp->para[1])));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 107, (long) ((const vector<Detector,allocator<Detector> >*) G__getstructoffset())->capacity());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    G__letint(result7, 103, (long) ((const vector<Detector,allocator<Detector> >*) G__getstructoffset())->empty());
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        const vector<Detector,allocator<Detector> >::reference obj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->operator[]((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::const_reference obj = ((const vector<Detector,allocator<Detector> >*) G__getstructoffset())->operator[]((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    vector<Detector,allocator<Detector> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    int n = G__getaryconstruct();
    if (n) {
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
            p = new vector<Detector,allocator<Detector> >[n];
        } else {
            p = new((void*) gvp) vector<Detector,allocator<Detector> >[n];
        }
    } else {
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
            p = new vector<Detector,allocator<Detector> >;
        } else {
            p = new((void*) gvp) vector<Detector,allocator<Detector> >;
        }
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    vector<Detector,allocator<Detector> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    switch (libp->paran) {
    case 2:
        //m: 2
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
            p = new vector<Detector,allocator<Detector> >((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]), *(Detector*) libp->para[1].ref);
        } else {
            p = new((void*) gvp) vector<Detector,allocator<Detector> >((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]), *(Detector*) libp->para[1].ref);
        }
        break;
    case 1:
        //m: 1
        if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
            p = new vector<Detector,allocator<Detector> >((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
        } else {
            p = new((void*) gvp) vector<Detector,allocator<Detector> >((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
        }
        break;
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    vector<Detector,allocator<Detector> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 1
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<Detector,allocator<Detector> >(*(vector<Detector,allocator<Detector> >*) libp->para[0].ref);
    } else {
        p = new((void*) gvp) vector<Detector,allocator<Detector> >(*(vector<Detector,allocator<Detector> >*) libp->para[0].ref);
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    vector<Detector,allocator<Detector> >* p = NULL;
    char* gvp = (char*) G__getgvp();
    //m: 2
    if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
        p = new vector<Detector,allocator<Detector> >(*((vector<Detector,allocator<Detector> >::const_iterator*) G__int(libp->para[0])), *((vector<Detector,allocator<Detector> >::const_iterator*) G__int(libp->para[1])));
    } else {
        p = new((void*) gvp) vector<Detector,allocator<Detector> >(*((vector<Detector,allocator<Detector> >::const_iterator*) G__int(libp->para[0])), *((vector<Detector,allocator<Detector> >::const_iterator*) G__int(libp->para[1])));
    }
    result7->obj.i = (long) p;
    result7->ref = (long) p;
    G__set_tagnum(result7,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        const vector<Detector,allocator<Detector> >& obj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->operator=(*(vector<Detector,allocator<Detector> >*) libp->para[0].ref);
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->reserve((vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[0]));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        const Detector& obj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->front();
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        const Detector& obj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->back();
        result7->ref = (long) (&obj);
        result7->obj.i = (long) (&obj);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->push_back(*(Detector*) libp->para[0].ref);
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->swap(*(vector<Detector,allocator<Detector> >*) libp->para[0].ref);
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    {
        vector<Detector,allocator<Detector> >::iterator* pobj;
        vector<Detector,allocator<Detector> >::iterator xobj = ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->insert(*((vector<Detector,allocator<Detector> >::iterator*) G__int(libp->para[0])), *(Detector*) libp->para[1].ref);
        pobj = new vector<Detector,allocator<Detector> >::iterator(xobj);
        result7->obj.i = (long) ((void*) pobj);
        result7->ref = result7->obj.i;
        G__store_tempobject(*result7);
    }
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->insert(*((vector<Detector,allocator<Detector> >::iterator*) G__int(libp->para[0])), *((vector<Detector,allocator<Detector> >::const_iterator*) G__int(libp->para[1]))
                                                                            , *((vector<Detector,allocator<Detector> >::const_iterator*) G__int(libp->para[2])));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->insert(*((vector<Detector,allocator<Detector> >::iterator*) G__int(libp->para[0])), (vector<Detector,allocator<Detector> >::size_type) G__int(libp->para[1])
                                                                            , *(Detector*) libp->para[2].ref);
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->pop_back();
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->erase(*((vector<Detector,allocator<Detector> >::iterator*) G__int(libp->para[0])));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->erase(*((vector<Detector,allocator<Detector> >::iterator*) G__int(libp->para[0])), *((vector<Detector,allocator<Detector> >::iterator*) G__int(libp->para[1])));
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

static int G__NTupleDictionary_222_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    ((vector<Detector,allocator<Detector> >*) G__getstructoffset())->clear();
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vector<Detector,allocator<Detector> > G__TvectorlEDetectorcOallocatorlEDetectorgRsPgR;
static int G__NTupleDictionary_222_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
    char* gvp = (char*) G__getgvp();
    long soff = G__getstructoffset();
    int n = G__getaryconstruct();
    //
    //has_a_delete: 0
    //has_own_delete1arg: 0
    //has_own_delete2arg: 0
    //
    if (!soff) {
        return(1);
    }
    if (n) {
        if (gvp == (char*)G__PVOID) {
            delete[] (vector<Detector,allocator<Detector> >*) soff;
        } else {
            G__setgvp((long) G__PVOID);
            for (int i = n - 1; i >= 0; --i) {
                ((vector<Detector,allocator<Detector> >*) (soff+(sizeof(vector<Detector,allocator<Detector> >)*i)))->~G__TvectorlEDetectorcOallocatorlEDetectorgRsPgR();
            }
            G__setgvp((long)gvp);
        }
    } else {
        if (gvp == (char*)G__PVOID) {
            delete (vector<Detector,allocator<Detector> >*) soff;
        } else {
            G__setgvp((long) G__PVOID);
            ((vector<Detector,allocator<Detector> >*) (soff))->~G__TvectorlEDetectorcOallocatorlEDetectorgRsPgR();
            G__setgvp((long)gvp);
        }
    }
    G__setnull(result7);
    return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Detector */

/* vector<Detector,allocator<Detector> > */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNTupleDictionary {
public:
    G__Sizep2memfuncNTupleDictionary(): p(&G__Sizep2memfuncNTupleDictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
private:
    size_t (G__Sizep2memfuncNTupleDictionary::*p)();
};

size_t G__get_sizep2memfuncNTupleDictionary()
{
    G__Sizep2memfuncNTupleDictionary a;
    G__setsizep2memfunc((int)a.sizep2memfunc());
    return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

/* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNTupleDictionary() {

    /* Setting up class inheritance */
    if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector))) {
        Detector *G__Lderived;
        G__Lderived=(Detector*)0x1000;
        {
            TObject *G__Lpbase=(TObject*)G__Lderived;
            G__inheritance_setup(G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector),G__get_linked_tagnum(&G__NTupleDictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
        }
    }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNTupleDictionary() {

    /* Setting up typedef entry */
    G__search_typename2("Version_t",115,-1,0,-1);
    G__setnewtype(-1,"Class version identifier (short)",0);
    G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTBaselEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTBaselEdoublegR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TVectorTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TVectorTlEdoublegR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTRow_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTColumn_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTDiag_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTFlat_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTSub_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTRowlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTColumnlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTDiaglEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTFlatlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTSublEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTSparseRowlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TMatrixTSparseDiaglEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TElementActionTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_TElementPosActionTlEfloatgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("vector<Detector>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR),0,-1);
    G__setnewtype(-1,NULL,0);
    G__search_typename2("value_type",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("pointer",85,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_pointer",85,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector),256,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reference",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector),1,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reference",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector),257,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("size_type",107,-1,0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("difference_type",108,-1,0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_iterator",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator),256,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("const_reverse_iterator",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
    G__search_typename2("reverse_iterator",117,G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

/* Setting up class,struct,union tag member variable */

/* Detector */
static void G__setup_memvarDetector(void) {
    G__tag_memvar_setup(G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector));
    { Detector *p; p=(Detector*)0x1000; if (p) { }
        G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fEventNumber=",0,(char*)NULL);
        G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fDetectorId=",0,(char*)NULL);
        G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fCrystalId=",0,(char*)NULL);
        G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fSimulationEnergy=",0,(char*)NULL);
        G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fEnergy=",0,(char*)NULL);
        G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__NTupleDictionaryLN_TVector3),-1,-1,4,"fPosition=",0,(char*)NULL);
        G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fTime=",0,(char*)NULL);
        G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NTupleDictionaryLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
    }
    G__tag_memvar_reset();
}


/* vector<Detector,allocator<Detector> > */
static void G__setup_memvarvectorlEDetectorcOallocatorlEDetectorgRsPgR(void) {
    G__tag_memvar_setup(G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    { vector<Detector,allocator<Detector> > *p; p=(vector<Detector,allocator<Detector> >*)0x1000; if (p) { }
    }
    G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNTupleDictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDetector(void) {
    /* Detector */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector));
    G__memfunc_setup("Detector",826,G__NTupleDictionary_220_0_1, 105, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Detector",826,G__NTupleDictionary_220_0_2, 105, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), -1, 0, 7, 1, 1, 0,
                     "i - - 0 - evNumber i - - 0 - detNumber "
                     "i - - 0 - cryNumber d - - 0 - simEnergy "
                     "d - - 0 - energy u 'TVector3' - 0 - pos "
                     "d - - 0 - time", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("AddEnergy",883,G__NTupleDictionary_220_0_3, 121, -1, -1, 0, 2, 1, 1, 0,
                     "d - - 0 - simEnergy d - - 0 - energy", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Set",300,G__NTupleDictionary_220_0_4, 121, -1, -1, 0, 7, 1, 1, 0,
                     "i - - 0 - evNumber i - - 0 - detNumber "
                     "i - - 0 - cryNumber d - - 0 - simEnergy "
                     "d - - 0 - energy u 'TVector3' - 0 - pos "
                     "d - - 0 - time", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Clear",487,G__NTupleDictionary_220_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("EventNumber",1131,G__NTupleDictionary_220_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DetectorId",999,G__NTupleDictionary_220_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("CrystalId",911,G__NTupleDictionary_220_0_8, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("SimulationEnergy",1679,G__NTupleDictionary_220_0_9, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Energy",618,G__NTupleDictionary_220_0_10, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Position",853,G__NTupleDictionary_220_0_11, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_TVector3), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Time",399,G__NTupleDictionary_220_0_12, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("Class",502,G__NTupleDictionary_220_0_13, 85, G__get_linked_tagnum(&G__NTupleDictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Detector::Class) ), 0);
    G__memfunc_setup("Class_Name",982,G__NTupleDictionary_220_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Detector::Class_Name) ), 0);
    G__memfunc_setup("Class_Version",1339,G__NTupleDictionary_220_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Detector::Class_Version) ), 0);
    G__memfunc_setup("Dictionary",1046,G__NTupleDictionary_220_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Detector::Dictionary) ), 0);
    G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__NTupleDictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
    G__memfunc_setup("StreamerNVirtual",1656,G__NTupleDictionary_220_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("DeclFileName",1145,G__NTupleDictionary_220_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Detector::DeclFileName) ), 0);
    G__memfunc_setup("ImplFileLine",1178,G__NTupleDictionary_220_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Detector::ImplFileLine) ), 0);
    G__memfunc_setup("ImplFileName",1171,G__NTupleDictionary_220_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Detector::ImplFileName) ), 0);
    G__memfunc_setup("DeclFileLine",1152,G__NTupleDictionary_220_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Detector::DeclFileLine) ), 0);
    // automatic copy constructor
    G__memfunc_setup("Detector", 826, G__NTupleDictionary_220_0_25, (int) ('i'), G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), -1, 0, 1, 1, 1, 0, "u 'Detector' - 11 - -", (char*) NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~Detector", 952, G__NTupleDictionary_220_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
    // automatic assignment operator
    G__memfunc_setup("operator=", 937, G__NTupleDictionary_220_0_27, (int) ('u'), G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), -1, 1, 1, 1, 1, 0, "u 'Detector' - 11 - -", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
}

static void G__setup_memfuncvectorlEDetectorcOallocatorlEDetectorgRsPgR(void) {
    /* vector<Detector,allocator<Detector> > */
    G__tag_memfunc_setup(G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR));
    G__memfunc_setup("at",213,G__NTupleDictionary_222_0_1, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), G__defined_typename("vector<Detector,allocator<Detector> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("at",213,G__NTupleDictionary_222_0_2, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), G__defined_typename("vector<Detector,allocator<Detector> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("begin",517,G__NTupleDictionary_222_0_3, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("end",311,G__NTupleDictionary_222_0_4, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rbegin",631,G__NTupleDictionary_222_0_5, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR), G__defined_typename("vector<Detector,allocator<Detector> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("rend",425,G__NTupleDictionary_222_0_6, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR), G__defined_typename("vector<Detector,allocator<Detector> >::reverse_iterator"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("size",443,G__NTupleDictionary_222_0_7, 107, -1, G__defined_typename("vector<Detector,allocator<Detector> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("max_size",864,G__NTupleDictionary_222_0_8, 107, -1, G__defined_typename("vector<Detector,allocator<Detector> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__NTupleDictionary_222_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - sz", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("resize",658,G__NTupleDictionary_222_0_10, 121, -1, -1, 0, 2, 1, 1, 0,
                     "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - sz u 'Detector' - 0 - c", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("capacity",846,G__NTupleDictionary_222_0_11, 107, -1, G__defined_typename("vector<Detector,allocator<Detector> >::size_type"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("empty",559,G__NTupleDictionary_222_0_12, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__NTupleDictionary_222_0_13, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), G__defined_typename("vector<Detector,allocator<Detector> >::reference"), 1, 1, 1, 1, 0, "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator[]",1060,G__NTupleDictionary_222_0_14, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), G__defined_typename("vector<Detector,allocator<Detector> >::const_reference"), 1, 1, 1, 1, 8, "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<Detector,allocator<Detector> >",3592,G__NTupleDictionary_222_0_15, 105, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<Detector,allocator<Detector> >",3592,G__NTupleDictionary_222_0_16, 105, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR), -1, 0, 2, 1, 1, 0,
                     "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n u 'Detector' - 11 'Detector()' value", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<Detector,allocator<Detector> >",3592,G__NTupleDictionary_222_0_17, 105, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR), -1, 0, 1, 1, 1, 0, "u 'vector<Detector,allocator<Detector> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("vector<Detector,allocator<Detector> >",3592,G__NTupleDictionary_222_0_18, 105, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR), -1, 0, 2, 1, 1, 0,
                     "u 'vector<Detector,allocator<Detector> >::iterator' 'vector<Detector,allocator<Detector> >::const_iterator' 10 - first u 'vector<Detector,allocator<Detector> >::iterator' 'vector<Detector,allocator<Detector> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("operator=",937,G__NTupleDictionary_222_0_19, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR), -1, 1, 1, 1, 1, 0, "u 'vector<Detector,allocator<Detector> >' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("reserve",764,G__NTupleDictionary_222_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("front",553,G__NTupleDictionary_222_0_21, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("back",401,G__NTupleDictionary_222_0_22, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_Detector), -1, 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("push_back",944,G__NTupleDictionary_222_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'Detector' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("swap",443,G__NTupleDictionary_222_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<Detector,allocator<Detector> >' - 1 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__NTupleDictionary_222_0_25, 117, G__get_linked_tagnum(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator), -1, 0, 2, 1, 1, 0,
                     "u 'vector<Detector,allocator<Detector> >::iterator' - 0 - position u 'Detector' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__NTupleDictionary_222_0_26, 121, -1, -1, 0, 3, 1, 1, 0,
                     "u 'vector<Detector,allocator<Detector> >::iterator' - 0 - position u 'vector<Detector,allocator<Detector> >::iterator' 'vector<Detector,allocator<Detector> >::const_iterator' 10 - first "
                     "u 'vector<Detector,allocator<Detector> >::iterator' 'vector<Detector,allocator<Detector> >::const_iterator' 10 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("insert",661,G__NTupleDictionary_222_0_27, 121, -1, -1, 0, 3, 1, 1, 0,
                     "u 'vector<Detector,allocator<Detector> >::iterator' - 0 - position k - 'vector<Detector,allocator<Detector> >::size_type' 0 - n "
                     "u 'Detector' - 11 - x", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("pop_back",831,G__NTupleDictionary_222_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__NTupleDictionary_222_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<Detector,allocator<Detector> >::iterator' - 0 - position", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("erase",528,G__NTupleDictionary_222_0_30, 121, -1, -1, 0, 2, 1, 1, 0,
                     "u 'vector<Detector,allocator<Detector> >::iterator' - 0 - first u 'vector<Detector,allocator<Detector> >::iterator' - 0 - last", (char*)NULL, (void*) NULL, 0);
    G__memfunc_setup("clear",519,G__NTupleDictionary_222_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
    // automatic destructor
    G__memfunc_setup("~vector<Detector,allocator<Detector> >", 3718, G__NTupleDictionary_222_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
    G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNTupleDictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

    /* Setting up global variables */
    G__resetplocal();

}

static void G__cpp_setup_global1() {

    G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNTupleDictionary() {
    G__cpp_setup_global0();
    G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
    G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

    G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNTupleDictionary() {
    G__cpp_setup_func0();
    G__cpp_setup_func1();
    G__cpp_setup_func2();
    G__cpp_setup_func3();
    G__cpp_setup_func4();
    G__cpp_setup_func5();
    G__cpp_setup_func6();
    G__cpp_setup_func7();
    G__cpp_setup_func8();
    G__cpp_setup_func9();
    G__cpp_setup_func10();
    G__cpp_setup_func11();
    G__cpp_setup_func12();
    G__cpp_setup_func13();
    G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NTupleDictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_Detector = { "Detector" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR = { "vector<Detector,allocator<Detector> >" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator = { "vector<Detector,allocator<Detector> >::iterator" , 99 , -1 };
G__linked_taginfo G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Detector,allocator<Detector> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNTupleDictionary() {
    G__NTupleDictionaryLN_TClass.tagnum = -1 ;
    G__NTupleDictionaryLN_TBuffer.tagnum = -1 ;
    G__NTupleDictionaryLN_TMemberInspector.tagnum = -1 ;
    G__NTupleDictionaryLN_TObject.tagnum = -1 ;
    G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
    G__NTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
    G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
    G__NTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
    G__NTupleDictionaryLN_TVectorTlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TVectorTlEdoublegR.tagnum = -1 ;
    G__NTupleDictionaryLN_TElementActionTlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTSublEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
    G__NTupleDictionaryLN_TVector3.tagnum = -1 ;
    G__NTupleDictionaryLN_Detector.tagnum = -1 ;
    G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR.tagnum = -1 ;
    G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator.tagnum = -1 ;
    G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNTupleDictionary() {

    /* Setting up class,struct,union tag entry */
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TClass);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TBuffer);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMemberInspector);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TObject);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTBaselEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTBaselEdoublegR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TVectorTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TVectorTlEdoublegR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TElementActionTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TElementPosActionTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTRow_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTRowlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTDiag_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTColumn_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTFlat_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTSub_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTSparseRow_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTSparseDiag_constlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTColumnlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTDiaglEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTFlatlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTSublEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTSparseRowlEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TMatrixTSparseDiaglEfloatgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_TVector3);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_Detector),sizeof(Detector),-1,324864,(char*)NULL,G__setup_memvarDetector,G__setup_memfuncDetector);
    G__tagtable_setup(G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR),sizeof(vector<Detector,allocator<Detector> >),-1,298752,(char*)NULL,G__setup_memvarvectorlEDetectorcOallocatorlEDetectorgRsPgR,G__setup_memfuncvectorlEDetectorcOallocatorlEDetectorgRsPgR);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator);
    G__get_linked_tagnum_fwd(&G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupNTupleDictionary(void) {
    G__check_setup_version(30051515,"G__cpp_setupNTupleDictionary()");
    G__set_cpp_environmentNTupleDictionary();
    G__cpp_setup_tagtableNTupleDictionary();

    G__cpp_setup_inheritanceNTupleDictionary();

    G__cpp_setup_typetableNTupleDictionary();

    G__cpp_setup_memvarNTupleDictionary();

    G__cpp_setup_memfuncNTupleDictionary();
    G__cpp_setup_globalNTupleDictionary();
    G__cpp_setup_funcNTupleDictionary();

    if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNTupleDictionary();
    return;
}
class G__cpp_setup_initNTupleDictionary {
public:
    G__cpp_setup_initNTupleDictionary() { G__add_setup_func("NTupleDictionary",(G__incsetup)(&G__cpp_setupNTupleDictionary)); G__call_setup_funcs(); }
    ~G__cpp_setup_initNTupleDictionary() { G__remove_setup_func("NTupleDictionary"); }
};
G__cpp_setup_initNTupleDictionary G__cpp_setup_initializerNTupleDictionary;

