/********************************************************************
* NTupleDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NTupleDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableNTupleDictionary();
extern void G__cpp_setup_inheritanceNTupleDictionary();
extern void G__cpp_setup_typetableNTupleDictionary();
extern void G__cpp_setup_memvarNTupleDictionary();
extern void G__cpp_setup_globalNTupleDictionary();
extern void G__cpp_setup_memfuncNTupleDictionary();
extern void G__cpp_setup_funcNTupleDictionary();
extern void G__set_cpp_environmentNTupleDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Griffin.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NTupleDictionaryLN_TClass;
extern G__linked_taginfo G__NTupleDictionaryLN_TBuffer;
extern G__linked_taginfo G__NTupleDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__NTupleDictionaryLN_TObject;
extern G__linked_taginfo G__NTupleDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NTupleDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NTupleDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__NTupleDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__NTupleDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__NTupleDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__NTupleDictionaryLN_TVector3;
extern G__linked_taginfo G__NTupleDictionaryLN_Detector;
extern G__linked_taginfo G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgR;
extern G__linked_taginfo G__NTupleDictionaryLN_vectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiterator;
extern G__linked_taginfo G__NTupleDictionaryLN_reverse_iteratorlEvectorlEDetectorcOallocatorlEDetectorgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<Detector,allocator<Detector> > G__vectorlEDetectorcOallocatorlEDetectorgRsPgR;
